name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install mystmd
        run: npm install -g mystmd

      - name: Build the book
        run: myst build --html
        env:
          BASE_URL: /causal-inference-kr  # ✏️ 바꿔야 함: 본인 저장소 이름

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
